### ISSUE TITLE
Creación metodos MeterCarrito y VenderCarrito Clase Tienda

### ISSUE THREAD

**Issue by ivanacostadominguez** [PaSalva/EEDD_TIENDA#9]
Creación de métodos MeterCarrito y VenderCarrito de la clase Tienda

**Comment by lgraul87** [comment]
Empezando la tarea #9 Creación de métodos MeterCarrito y VenderCarrito de la clase Tienda

**Comment by PaSalva** [comment]
Revisa la tarea. Está mal subida. @lgraul87

**Comment by lgraul87** [comment]
Revisado
